"""
    Anvil Agent API

    Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "brokk-anvil-sdk"
VERSION = "0.25.0"
PYTHON_REQUIRES = ">= 3.10"
REQUIRES = [
    "python-dateutil >= 2.8.2",
    "aiohttp >= 3.8.4",
    "aiohttp-retry >= 2.8.3",
    "pydantic >= 2.11",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Anvil Agent API",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Anvil Agent API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="LGPL-3.0-only",
    long_description_content_type='text/markdown',
    long_description="""\
    Versioned REST surface of the Anvil agent runtime (&#x60;anvil serve&#x60;). This document, together with the companion SSE event schema (&#x60;anvil.v1.events.schema.json&#x60;), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (&#x60;tests/http_conformance.rs&#x60;) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within &#x60;/v1&#x60;.
    """,  # noqa: E501
    package_data={"brokk_anvil_sdk": ["py.typed"]},
)
