/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`get_permission`]
#[derive(Clone, Debug)]
pub struct GetPermissionParams {
    pub permission_id: String,
}

/// struct for passing parameters to the method [`list_run_permissions`]
#[derive(Clone, Debug)]
pub struct ListRunPermissionsParams {
    pub run_id: String,
}

/// struct for passing parameters to the method [`respond_permission`]
#[derive(Clone, Debug)]
pub struct RespondPermissionParams {
    pub permission_id: String,
    pub permission_response_request: models::PermissionResponseRequest,
}

/// struct for typed errors of method [`get_permission`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPermissionError {
    Status401(models::ErrorEnvelope),
    Status404(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_run_permissions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListRunPermissionsError {
    Status401(models::ErrorEnvelope),
    Status404(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`respond_permission`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RespondPermissionError {
    Status400(models::ErrorEnvelope),
    Status401(models::ErrorEnvelope),
    Status404(models::ErrorEnvelope),
    Status409(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

pub async fn get_permission(
    configuration: &configuration::Configuration,
    params: GetPermissionParams,
) -> Result<models::Permission, Error<GetPermissionError>> {
    let uri_str = format!(
        "{}/v1/permissions/{permission_id}",
        configuration.base_path,
        permission_id = crate::apis::urlencode(params.permission_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Permission`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Permission`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetPermissionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn list_run_permissions(
    configuration: &configuration::Configuration,
    params: ListRunPermissionsParams,
) -> Result<models::PermissionListResponse, Error<ListRunPermissionsError>> {
    let uri_str = format!(
        "{}/v1/runs/{run_id}/permissions",
        configuration.base_path,
        run_id = crate::apis::urlencode(params.run_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PermissionListResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PermissionListResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListRunPermissionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Resolves a pending request exactly once. `option_id` must be one of the ids offered on the request (for example `allow`, `allow_always`, `allow_outside_sandbox`, `reject`); alternatively pass `cancel: true` to cancel the request. Requests that were already resolved — including by run cancellation or completion — answer 404 (no longer pending) or 409 (racing resolution).
pub async fn respond_permission(
    configuration: &configuration::Configuration,
    params: RespondPermissionParams,
) -> Result<models::PermissionRespondResult, Error<RespondPermissionError>> {
    let uri_str = format!(
        "{}/v1/permissions/{permission_id}/respond",
        configuration.base_path,
        permission_id = crate::apis::urlencode(params.permission_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.permission_response_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PermissionRespondResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PermissionRespondResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RespondPermissionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
