/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`cancel_run`]
#[derive(Clone, Debug)]
pub struct CancelRunParams {
    pub run_id: String,
}

/// struct for passing parameters to the method [`create_run`]
#[derive(Clone, Debug)]
pub struct CreateRunParams {
    pub session_id: String,
    pub create_run_request: models::CreateRunRequest,
}

/// struct for passing parameters to the method [`get_run`]
#[derive(Clone, Debug)]
pub struct GetRunParams {
    pub run_id: String,
}

/// struct for passing parameters to the method [`list_runs`]
#[derive(Clone, Debug)]
pub struct ListRunsParams {
    pub session_id: String,
}

/// struct for passing parameters to the method [`stream_run_events`]
#[derive(Clone, Debug)]
pub struct StreamRunEventsParams {
    pub run_id: String,
    /// Replay events with sequence numbers greater than this. The `Last-Event-ID` header wins when both are present.
    pub after_seq: Option<u64>,
    pub last_event_id: Option<String>,
}

/// struct for typed errors of method [`cancel_run`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CancelRunError {
    Status401(models::ErrorEnvelope),
    Status404(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_run`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateRunError {
    Status400(models::ErrorEnvelope),
    Status401(models::ErrorEnvelope),
    Status404(models::ErrorEnvelope),
    Status409(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_run`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetRunError {
    Status401(models::ErrorEnvelope),
    Status404(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_runs`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListRunsError {
    Status401(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`stream_run_events`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StreamRunEventsError {
    Status401(models::ErrorEnvelope),
    Status404(models::ErrorEnvelope),
    UnknownValue(serde_json::Value),
}

/// Cancels through the same token the runtime uses for ACP cancellation. A cancel racing natural completion loses gracefully; cancelling a terminal run returns its current resource.
pub async fn cancel_run(
    configuration: &configuration::Configuration,
    params: CancelRunParams,
) -> Result<models::Run, Error<CancelRunError>> {
    let uri_str = format!(
        "{}/v1/runs/{run_id}/cancel",
        configuration.base_path,
        run_id = crate::apis::urlencode(params.run_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Run`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Run`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CancelRunError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Returns the run resource promptly; the turn executes in the background. One prompt may be in flight per session: a duplicate run is rejected with 409 until the active run reaches a terminal state or is cancelled. Progress is observable via the run's SSE event stream and by polling the run resource.
pub async fn create_run(
    configuration: &configuration::Configuration,
    params: CreateRunParams,
) -> Result<models::Run, Error<CreateRunError>> {
    let uri_str = format!(
        "{}/v1/sessions/{session_id}/runs",
        configuration.base_path,
        session_id = crate::apis::urlencode(params.session_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.create_run_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Run`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Run`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateRunError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn get_run(
    configuration: &configuration::Configuration,
    params: GetRunParams,
) -> Result<models::Run, Error<GetRunError>> {
    let uri_str = format!(
        "{}/v1/runs/{run_id}",
        configuration.base_path,
        run_id = crate::apis::urlencode(params.run_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Run`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Run`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetRunError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn list_runs(
    configuration: &configuration::Configuration,
    params: ListRunsParams,
) -> Result<models::RunListResponse, Error<ListRunsError>> {
    let uri_str = format!(
        "{}/v1/sessions/{session_id}/runs",
        configuration.base_path,
        session_id = crate::apis::urlencode(params.session_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RunListResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RunListResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListRunsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Ordered `text/event-stream`. Each SSE message carries the event's sequence number as its `id`, the event type as its `event` name, and a JSON payload described by the companion event schema (`anvil.v1.events.schema.json`) as its `data`. Reconnect with the standard `Last-Event-ID` header (or the `after_seq` query parameter) to replay from a bounded per-run buffer; falling behind the buffer yields an `events.gap` notice. The stream ends after the terminal `run.*` event. Dropping the stream never cancels the run.
pub async fn stream_run_events(
    configuration: &configuration::Configuration,
    params: StreamRunEventsParams,
) -> Result<models::AnvilRunEvent, Error<StreamRunEventsError>> {
    let uri_str = format!(
        "{}/v1/runs/{run_id}/events",
        configuration.base_path,
        run_id = crate::apis::urlencode(params.run_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.after_seq {
        req_builder = req_builder.query(&[("after_seq", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.last_event_id {
        req_builder = req_builder.header("Last-Event-ID", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AnvilRunEvent`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AnvilRunEvent`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StreamRunEventsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
