/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AnvilRunEvent : Contract for the JSON payload carried in each Server-Sent Event on GET /v1/runs/{run_id}/events. The SSE `id` field is the decimal `seq`; the SSE `event` field equals `type`. Every event shares the envelope fields and one payload variant selected by `type`. The stream ends after a terminal `run.completed`, `run.cancelled`, or `run.failed` event. The synthetic `events.gap` notice is emitted without an envelope `seq` when a reconnect falls behind the bounded replay buffer.
/// Contract for the JSON payload carried in each Server-Sent Event on GET /v1/runs/{run_id}/events. The SSE `id` field is the decimal `seq`; the SSE `event` field equals `type`. Every event shares the envelope fields and one payload variant selected by `type`. The stream ends after a terminal `run.completed`, `run.cancelled`, or `run.failed` event. The synthetic `events.gap` notice is emitted without an envelope `seq` when a reconnect falls behind the bounded replay buffer.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AnvilRunEvent {
    EventRunCreated(Box<models::EventRunCreated>),
    EventMessageDelta(Box<models::EventMessageDelta>),
    EventThoughtDelta(Box<models::EventThoughtDelta>),
    EventPlanUpdated(Box<models::EventPlanUpdated>),
    EventToolCallStarted(Box<models::EventToolCallStarted>),
    EventToolCallBlocked(Box<models::EventToolCallBlocked>),
    EventToolCallInProgress(Box<models::EventToolCallInProgress>),
    EventToolCallFailed(Box<models::EventToolCallFailed>),
    EventToolCallCompleted(Box<models::EventToolCallCompleted>),
    EventPermissionRequested(Box<models::EventPermissionRequested>),
    EventPermissionResolved(Box<models::EventPermissionResolved>),
    EventRunTerminal(Box<models::EventRunTerminal>),
    EventEventsGap(Box<models::EventEventsGap>),
}

impl Default for AnvilRunEvent {
    fn default() -> Self {
        Self::EventRunCreated(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StopReason {
    #[serde(rename = "end_turn")]
    EndTurn,
    #[serde(rename = "max_turns")]
    MaxTurns,
    #[serde(rename = "time_limit")]
    TimeLimit,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "error")]
    Error,
}

impl Default for StopReason {
    fn default() -> StopReason {
        Self::EndTurn
    }
}
