/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRunRequest {
    #[serde(rename = "prompt")]
    pub prompt: String,
    #[serde(
        rename = "structured_output",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub structured_output: Option<Option<Box<models::StructuredOutputSpec>>>,
}

impl CreateRunRequest {
    pub fn new(prompt: String) -> CreateRunRequest {
        CreateRunRequest {
            prompt,
            structured_output: None,
        }
    }
}
