/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ErrorEnvelope : Stable envelope for every non-2xx JSON response. The `request_id` is also echoed on every response in the `x-request-id` header.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorEnvelope {
    #[serde(rename = "error")]
    pub error: Box<models::ErrorEnvelopeError>,
    #[serde(rename = "request_id", deserialize_with = "Option::deserialize")]
    pub request_id: Option<String>,
}

impl ErrorEnvelope {
    /// Stable envelope for every non-2xx JSON response. The `request_id` is also echoed on every response in the `x-request-id` header.
    pub fn new(error: models::ErrorEnvelopeError, request_id: Option<String>) -> ErrorEnvelope {
        ErrorEnvelope {
            error: Box::new(error),
            request_id,
        }
    }
}
