/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventToolCallCompletedAllOfDiff {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "old_text", deserialize_with = "Option::deserialize")]
    pub old_text: Option<String>,
    #[serde(rename = "new_text")]
    pub new_text: String,
}

impl EventToolCallCompletedAllOfDiff {
    pub fn new(
        path: String,
        old_text: Option<String>,
        new_text: String,
    ) -> EventToolCallCompletedAllOfDiff {
        EventToolCallCompletedAllOfDiff {
            path,
            old_text,
            new_text,
        }
    }
}
