/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventRunTerminal {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "run_id")]
    pub run_id: String,
    #[serde(rename = "session_id")]
    pub session_id: String,
    #[serde(rename = "seq")]
    pub seq: i64,
    #[serde(rename = "ts_ms")]
    pub ts_ms: i64,
    #[serde(rename = "stop_reason", deserialize_with = "Option::deserialize")]
    pub stop_reason: Option<StopReason>,
    #[serde(
        rename = "error",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<Option<String>>,
    #[serde(
        rename = "result_text",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub result_text: Option<Option<String>>,
    #[serde(
        rename = "structured_output",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub structured_output: Option<Option<serde_json::Value>>,
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Box<models::EventUsage>>,
    #[serde(rename = "cumulative_usage", skip_serializing_if = "Option::is_none")]
    pub cumulative_usage: Option<Box<models::EventUsage>>,
}

impl EventRunTerminal {
    pub fn new(
        r#type: Type,
        run_id: String,
        session_id: String,
        seq: i64,
        ts_ms: i64,
        stop_reason: Option<StopReason>,
    ) -> EventRunTerminal {
        EventRunTerminal {
            r#type,
            run_id,
            session_id,
            seq,
            ts_ms,
            stop_reason,
            error: None,
            result_text: None,
            structured_output: None,
            usage: None,
            cumulative_usage: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "run.completed")]
    RunCompleted,
    #[serde(rename = "run.cancelled")]
    RunCancelled,
    #[serde(rename = "run.failed")]
    RunFailed,
}

impl Default for Type {
    fn default() -> Type {
        Self::RunCompleted
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StopReason {
    #[serde(rename = "end_turn")]
    EndTurn,
    #[serde(rename = "max_turns")]
    MaxTurns,
    #[serde(rename = "time_limit")]
    TimeLimit,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "error")]
    Error,
}

impl Default for StopReason {
    fn default() -> StopReason {
        Self::EndTurn
    }
}
