/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPermissionRequested {
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<serde_json::Value>,
    #[serde(rename = "run_id")]
    pub run_id: String,
    #[serde(rename = "session_id")]
    pub session_id: String,
    #[serde(rename = "seq")]
    pub seq: i64,
    #[serde(rename = "ts_ms")]
    pub ts_ms: i64,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "permission_id")]
    pub permission_id: String,
    #[serde(rename = "tool_name")]
    pub tool_name: String,
    #[serde(rename = "tool_call_id")]
    pub tool_call_id: String,
    #[serde(
        rename = "input",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub input: Option<Option<serde_json::Value>>,
    #[serde(
        rename = "permission_notice",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub permission_notice: Option<Option<String>>,
    #[serde(rename = "options")]
    pub options: Vec<models::EventPermissionRequestedAllOfOptions>,
    #[serde(rename = "created_at_ms", skip_serializing_if = "Option::is_none")]
    pub created_at_ms: Option<u64>,
}

impl EventPermissionRequested {
    pub fn new(
        r#type: Option<serde_json::Value>,
        run_id: String,
        session_id: String,
        seq: i64,
        ts_ms: i64,
        permission_id: String,
        tool_name: String,
        tool_call_id: String,
        options: Vec<models::EventPermissionRequestedAllOfOptions>,
    ) -> EventPermissionRequested {
        EventPermissionRequested {
            r#type,
            run_id,
            session_id,
            seq,
            ts_ms,
            id: None,
            permission_id,
            tool_name,
            tool_call_id,
            input: None,
            permission_notice: None,
            options,
            created_at_ms: None,
        }
    }
}
