/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventEventsGap {
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<serde_json::Value>,
    #[serde(rename = "run_id")]
    pub run_id: String,
    #[serde(rename = "missed_through_seq")]
    pub missed_through_seq: u64,
}

impl EventEventsGap {
    pub fn new(
        r#type: Option<serde_json::Value>,
        run_id: String,
        missed_through_seq: u64,
    ) -> EventEventsGap {
        EventEventsGap {
            r#type,
            run_id,
            missed_through_seq,
        }
    }
}
