/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventEnvelope {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "run_id")]
    pub run_id: String,
    #[serde(rename = "session_id")]
    pub session_id: String,
    #[serde(rename = "seq")]
    pub seq: u64,
    #[serde(rename = "ts_ms")]
    pub ts_ms: u64,
}

impl EventEnvelope {
    pub fn new(
        r#type: String,
        run_id: String,
        session_id: String,
        seq: u64,
        ts_ms: u64,
    ) -> EventEnvelope {
        EventEnvelope {
            r#type,
            run_id,
            session_id,
            seq,
            ts_ms,
        }
    }
}
