/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Health {
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "name")]
    pub name: Name,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "models_discovered")]
    pub models_discovered: u64,
}

impl Health {
    pub fn new(status: Status, name: Name, version: String, models_discovered: u64) -> Health {
        Health {
            status,
            name,
            version,
            models_discovered,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ok")]
    Ok,
}

impl Default for Status {
    fn default() -> Status {
        Self::Ok
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Name {
    #[serde(rename = "anvil")]
    Anvil,
}

impl Default for Name {
    fn default() -> Name {
        Self::Anvil
    }
}
