/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoryTurnToolExchangesInner {
    #[serde(rename = "call_id")]
    pub call_id: String,
    #[serde(rename = "tool_name")]
    pub tool_name: String,
    #[serde(rename = "arguments")]
    pub arguments: String,
    #[serde(rename = "result")]
    pub result: String,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "permission_notice", deserialize_with = "Option::deserialize")]
    pub permission_notice: Option<String>,
}

impl HistoryTurnToolExchangesInner {
    pub fn new(
        call_id: String,
        tool_name: String,
        arguments: String,
        result: String,
        status: Status,
        permission_notice: Option<String>,
    ) -> HistoryTurnToolExchangesInner {
        HistoryTurnToolExchangesInner {
            call_id,
            tool_name,
            arguments,
            result,
            status,
            permission_notice,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Completed
    }
}
