/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoryTurn {
    #[serde(rename = "user_prompt")]
    pub user_prompt: String,
    #[serde(rename = "agent_response")]
    pub agent_response: String,
    #[serde(rename = "summary", deserialize_with = "Option::deserialize")]
    pub summary: Option<String>,
    #[serde(rename = "tool_exchanges")]
    pub tool_exchanges: Vec<models::HistoryTurnToolExchangesInner>,
}

impl HistoryTurn {
    pub fn new(
        user_prompt: String,
        agent_response: String,
        summary: Option<String>,
        tool_exchanges: Vec<models::HistoryTurnToolExchangesInner>,
    ) -> HistoryTurn {
        HistoryTurn {
            user_prompt,
            agent_response,
            summary,
            tool_exchanges,
        }
    }
}
