/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// McpServerConfig : Anvil's internal MCP server configuration shape. Per-session servers are additive to the daemon's canonical setup.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpServerConfig {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "transport", skip_serializing_if = "Option::is_none")]
    pub transport: Option<Transport>,
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<Vec<models::McpEnvVar>>,
    #[serde(rename = "args", skip_serializing_if = "Option::is_none")]
    pub args: Option<Vec<String>>,
    #[serde(rename = "env", skip_serializing_if = "Option::is_none")]
    pub env: Option<Vec<models::McpEnvVar>>,
    #[serde(rename = "framing", skip_serializing_if = "Option::is_none")]
    pub framing: Option<Framing>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl McpServerConfig {
    /// Anvil's internal MCP server configuration shape. Per-session servers are additive to the daemon's canonical setup.
    pub fn new(name: String) -> McpServerConfig {
        McpServerConfig {
            name,
            transport: None,
            command: None,
            url: None,
            headers: None,
            args: None,
            env: None,
            framing: None,
            enabled: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Transport {
    #[serde(rename = "stdio")]
    Stdio,
    #[serde(rename = "http")]
    Http,
    #[serde(rename = "sse")]
    Sse,
}

impl Default for Transport {
    fn default() -> Transport {
        Self::Stdio
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Framing {
    #[serde(rename = "content-length")]
    ContentLength,
    #[serde(rename = "line")]
    Line,
}

impl Default for Framing {
    fn default() -> Framing {
        Self::ContentLength
    }
}
