/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Model : One discovered model. Ids are wire-tagged `<source>::<id>` (for example `codex::gpt-5-codex`, `ollama::llama3:latest`).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(
        rename = "default_reasoning_level",
        deserialize_with = "Option::deserialize"
    )]
    pub default_reasoning_level: Option<String>,
    #[serde(rename = "supported_reasoning_levels")]
    pub supported_reasoning_levels: Vec<models::ModelSupportedReasoningLevelsInner>,
    #[serde(rename = "service_tiers")]
    pub service_tiers: Vec<models::ModelServiceTiersInner>,
    #[serde(rename = "supports_images", deserialize_with = "Option::deserialize")]
    pub supports_images: Option<bool>,
    #[serde(rename = "context_length", deserialize_with = "Option::deserialize")]
    pub context_length: Option<u64>,
    #[serde(rename = "pricing", deserialize_with = "Option::deserialize")]
    pub pricing: Option<Box<models::ModelPricing>>,
}

impl Model {
    /// One discovered model. Ids are wire-tagged `<source>::<id>` (for example `codex::gpt-5-codex`, `ollama::llama3:latest`).
    pub fn new(
        id: String,
        default_reasoning_level: Option<String>,
        supported_reasoning_levels: Vec<models::ModelSupportedReasoningLevelsInner>,
        service_tiers: Vec<models::ModelServiceTiersInner>,
        supports_images: Option<bool>,
        context_length: Option<u64>,
        pricing: Option<models::ModelPricing>,
    ) -> Model {
        Model {
            id,
            default_reasoning_level,
            supported_reasoning_levels,
            service_tiers,
            supports_images,
            context_length,
            pricing: if let Some(x) = pricing {
                Some(Box::new(x))
            } else {
                None
            },
        }
    }
}
