/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsResponse {
    #[serde(rename = "models")]
    pub models: Vec<models::Model>,
    #[serde(rename = "default_model", deserialize_with = "Option::deserialize")]
    pub default_model: Option<String>,
}

impl ModelsResponse {
    pub fn new(models: Vec<models::Model>, default_model: Option<String>) -> ModelsResponse {
        ModelsResponse {
            models,
            default_model,
        }
    }
}
