/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Permission {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "run_id")]
    pub run_id: String,
    #[serde(rename = "session_id")]
    pub session_id: String,
    #[serde(rename = "tool_name")]
    pub tool_name: String,
    #[serde(rename = "tool_call_id")]
    pub tool_call_id: String,
    #[serde(rename = "input", deserialize_with = "Option::deserialize")]
    pub input: Option<serde_json::Value>,
    #[serde(rename = "permission_notice", deserialize_with = "Option::deserialize")]
    pub permission_notice: Option<String>,
    #[serde(rename = "options")]
    pub options: Vec<models::PermissionOption>,
    #[serde(rename = "created_at_ms")]
    pub created_at_ms: u64,
    #[serde(rename = "status")]
    pub status: Status,
}

impl Permission {
    pub fn new(
        id: String,
        run_id: String,
        session_id: String,
        tool_name: String,
        tool_call_id: String,
        input: Option<serde_json::Value>,
        permission_notice: Option<String>,
        options: Vec<models::PermissionOption>,
        created_at_ms: u64,
        status: Status,
    ) -> Permission {
        Permission {
            id,
            run_id,
            session_id,
            tool_name,
            tool_call_id,
            input,
            permission_notice,
            options,
            created_at_ms,
            status,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "pending")]
    Pending,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pending
    }
}
