/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Run {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "session_id")]
    pub session_id: String,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "stop_reason", deserialize_with = "Option::deserialize")]
    pub stop_reason: Option<StopReason>,
    #[serde(rename = "error", deserialize_with = "Option::deserialize")]
    pub error: Option<String>,
    #[serde(rename = "result_text", deserialize_with = "Option::deserialize")]
    pub result_text: Option<String>,
    #[serde(rename = "structured_output", deserialize_with = "Option::deserialize")]
    pub structured_output: Option<serde_json::Value>,
    #[serde(rename = "usage", deserialize_with = "Option::deserialize")]
    pub usage: Option<Box<models::Usage>>,
    #[serde(rename = "created_at_ms")]
    pub created_at_ms: u64,
    #[serde(rename = "finished_at_ms", deserialize_with = "Option::deserialize")]
    pub finished_at_ms: Option<u64>,
    #[serde(rename = "last_seq")]
    pub last_seq: u64,
}

impl Run {
    pub fn new(
        id: String,
        session_id: String,
        status: Status,
        stop_reason: Option<StopReason>,
        error: Option<String>,
        result_text: Option<String>,
        structured_output: Option<serde_json::Value>,
        usage: Option<models::Usage>,
        created_at_ms: u64,
        finished_at_ms: Option<u64>,
        last_seq: u64,
    ) -> Run {
        Run {
            id,
            session_id,
            status,
            stop_reason,
            error,
            result_text,
            structured_output,
            usage: if let Some(x) = usage {
                Some(Box::new(x))
            } else {
                None
            },
            created_at_ms,
            finished_at_ms,
            last_seq,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Running
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StopReason {
    #[serde(rename = "end_turn")]
    EndTurn,
    #[serde(rename = "max_turns")]
    MaxTurns,
    #[serde(rename = "time_limit")]
    TimeLimit,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "error")]
    Error,
}

impl Default for StopReason {
    fn default() -> StopReason {
        Self::EndTurn
    }
}
