/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionListResponseSessionsInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "title", deserialize_with = "Option::deserialize")]
    pub title: Option<String>,
    #[serde(rename = "created_at_ms")]
    pub created_at_ms: u64,
    #[serde(rename = "modified_at_ms")]
    pub modified_at_ms: u64,
    #[serde(rename = "updated_at", deserialize_with = "Option::deserialize")]
    pub updated_at: Option<String>,
    #[serde(rename = "cwd", deserialize_with = "Option::deserialize")]
    pub cwd: Option<String>,
    #[serde(rename = "resident")]
    pub resident: bool,
}

impl SessionListResponseSessionsInner {
    pub fn new(
        id: String,
        title: Option<String>,
        created_at_ms: u64,
        modified_at_ms: u64,
        updated_at: Option<String>,
        cwd: Option<String>,
        resident: bool,
    ) -> SessionListResponseSessionsInner {
        SessionListResponseSessionsInner {
            id,
            title,
            created_at_ms,
            modified_at_ms,
            updated_at,
            cwd,
            resident,
        }
    }
}
