/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Session {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "cwd")]
    pub cwd: String,
    #[serde(rename = "additional_directories")]
    pub additional_directories: Vec<String>,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "behavior_mode")]
    pub behavior_mode: BehaviorMode,
    #[serde(rename = "permission_mode")]
    pub permission_mode: PermissionMode,
    #[serde(rename = "reasoning_effort", deserialize_with = "Option::deserialize")]
    pub reasoning_effort: Option<String>,
    #[serde(rename = "service_tier", deserialize_with = "Option::deserialize")]
    pub service_tier: Option<String>,
    #[serde(rename = "title", deserialize_with = "Option::deserialize")]
    pub title: Option<String>,
    #[serde(rename = "created_at_ms")]
    pub created_at_ms: u64,
    #[serde(rename = "modified_at_ms")]
    pub modified_at_ms: u64,
    /// RFC 3339 rendering of `modified_at_ms`.
    #[serde(rename = "updated_at", deserialize_with = "Option::deserialize")]
    pub updated_at: Option<String>,
    #[serde(rename = "history_turns")]
    pub history_turns: u64,
    #[serde(rename = "usage")]
    pub usage: Box<models::Usage>,
    #[serde(rename = "usage_cost_usd", deserialize_with = "Option::deserialize")]
    pub usage_cost_usd: Option<f64>,
    /// Present only on `load` responses and `?include_history=true` inspections.
    #[serde(rename = "history", skip_serializing_if = "Option::is_none")]
    pub history: Option<Vec<models::HistoryTurn>>,
}

impl Session {
    pub fn new(
        id: String,
        cwd: String,
        additional_directories: Vec<String>,
        model: String,
        behavior_mode: BehaviorMode,
        permission_mode: PermissionMode,
        reasoning_effort: Option<String>,
        service_tier: Option<String>,
        title: Option<String>,
        created_at_ms: u64,
        modified_at_ms: u64,
        updated_at: Option<String>,
        history_turns: u64,
        usage: models::Usage,
        usage_cost_usd: Option<f64>,
    ) -> Session {
        Session {
            id,
            cwd,
            additional_directories,
            model,
            behavior_mode,
            permission_mode,
            reasoning_effort,
            service_tier,
            title,
            created_at_ms,
            modified_at_ms,
            updated_at,
            history_turns,
            usage: Box::new(usage),
            usage_cost_usd,
            history: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BehaviorMode {
    #[serde(rename = "LUTZ")]
    Lutz,
    #[serde(rename = "PLAN")]
    Plan,
}

impl Default for BehaviorMode {
    fn default() -> BehaviorMode {
        Self::Lutz
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PermissionMode {
    #[serde(rename = "default")]
    Default,
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "acceptEdits")]
    AcceptEdits,
    #[serde(rename = "readOnly")]
    ReadOnly,
    #[serde(rename = "bypassPermissions")]
    BypassPermissions,
}

impl Default for PermissionMode {
    fn default() -> PermissionMode {
        Self::Default
    }
}
