/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SessionConfigPatch : Client-owned per-session selectors, mirroring the ACP `SessionConfigOption` ids. At least one property is required.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionConfigPatch {
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// A model-supported effort, `off` to omit reasoning controls, or empty string to clear back to the model default.
    #[serde(rename = "reasoning_effort", skip_serializing_if = "Option::is_none")]
    pub reasoning_effort: Option<String>,
    /// A provider tier id, or empty string to clear.
    #[serde(rename = "service_tier", skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<String>,
    #[serde(rename = "behavior_mode", skip_serializing_if = "Option::is_none")]
    pub behavior_mode: Option<BehaviorMode>,
    #[serde(rename = "permission_mode", skip_serializing_if = "Option::is_none")]
    pub permission_mode: Option<PermissionMode>,
}

impl SessionConfigPatch {
    /// Client-owned per-session selectors, mirroring the ACP `SessionConfigOption` ids. At least one property is required.
    pub fn new() -> SessionConfigPatch {
        SessionConfigPatch {
            model: None,
            reasoning_effort: None,
            service_tier: None,
            behavior_mode: None,
            permission_mode: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BehaviorMode {
    #[serde(rename = "LUTZ")]
    Lutz,
    #[serde(rename = "PLAN")]
    Plan,
}

impl Default for BehaviorMode {
    fn default() -> BehaviorMode {
        Self::Lutz
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PermissionMode {
    #[serde(rename = "default")]
    Default,
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "acceptEdits")]
    AcceptEdits,
    #[serde(rename = "readOnly")]
    ReadOnly,
    #[serde(rename = "bypassPermissions")]
    BypassPermissions,
}

impl Default for PermissionMode {
    fn default() -> PermissionMode {
        Self::Default
    }
}
