/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StructuredOutputSpec {
    #[serde(rename = "schema", deserialize_with = "Option::deserialize")]
    pub schema: Option<serde_json::Value>,
    #[serde(rename = "schema_name", skip_serializing_if = "Option::is_none")]
    pub schema_name: Option<String>,
    #[serde(rename = "allow_coercion", skip_serializing_if = "Option::is_none")]
    pub allow_coercion: Option<bool>,
    /// Request basic JSON mode instead of strict `json_schema` on providers that support only the former.
    #[serde(rename = "prefer_json_object", skip_serializing_if = "Option::is_none")]
    pub prefer_json_object: Option<bool>,
}

impl StructuredOutputSpec {
    pub fn new(schema: Option<serde_json::Value>) -> StructuredOutputSpec {
        StructuredOutputSpec {
            schema,
            schema_name: None,
            allow_coercion: None,
            prefer_json_object: None,
        }
    }
}
