/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tool {
    #[serde(rename = "name")]
    pub name: String,
    /// Permission-gate classification (ACP tool kind).
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "concurrency_safe")]
    pub concurrency_safe: bool,
    #[serde(rename = "source")]
    pub source: Source,
}

impl Tool {
    pub fn new(
        name: String,
        kind: String,
        display_name: String,
        concurrency_safe: bool,
        source: Source,
    ) -> Tool {
        Tool {
            name,
            kind,
            display_name,
            concurrency_safe,
            source,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Source {
    #[serde(rename = "builtin")]
    Builtin,
    #[serde(rename = "mcp")]
    Mcp,
}

impl Default for Source {
    fn default() -> Source {
        Self::Builtin
    }
}
