/*
 * Anvil Agent API
 *
 * Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Usage {
    #[serde(rename = "input_tokens")]
    pub input_tokens: u64,
    #[serde(rename = "output_tokens")]
    pub output_tokens: u64,
    #[serde(rename = "thought_tokens")]
    pub thought_tokens: u64,
    #[serde(rename = "cached_read_tokens")]
    pub cached_read_tokens: u64,
    #[serde(rename = "cached_write_tokens")]
    pub cached_write_tokens: u64,
}

impl Usage {
    pub fn new(
        input_tokens: u64,
        output_tokens: u64,
        thought_tokens: u64,
        cached_read_tokens: u64,
        cached_write_tokens: u64,
    ) -> Usage {
        Usage {
            input_tokens,
            output_tokens,
            thought_tokens,
            cached_read_tokens,
            cached_write_tokens,
        }
    }
}
