# coding: utf-8

"""
    Anvil Agent API

    Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from brokk_anvil_sdk.models.event_events_gap import EventEventsGap
from brokk_anvil_sdk.models.event_message_delta import EventMessageDelta
from brokk_anvil_sdk.models.event_permission_requested import EventPermissionRequested
from brokk_anvil_sdk.models.event_permission_resolved import EventPermissionResolved
from brokk_anvil_sdk.models.event_plan_updated import EventPlanUpdated
from brokk_anvil_sdk.models.event_run_created import EventRunCreated
from brokk_anvil_sdk.models.event_run_terminal import EventRunTerminal
from brokk_anvil_sdk.models.event_thought_delta import EventThoughtDelta
from brokk_anvil_sdk.models.event_tool_call_blocked import EventToolCallBlocked
from brokk_anvil_sdk.models.event_tool_call_completed import EventToolCallCompleted
from brokk_anvil_sdk.models.event_tool_call_failed import EventToolCallFailed
from brokk_anvil_sdk.models.event_tool_call_in_progress import EventToolCallInProgress
from brokk_anvil_sdk.models.event_tool_call_started import EventToolCallStarted
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

ANVILRUNEVENT_ONE_OF_SCHEMAS = ["EventEventsGap", "EventMessageDelta", "EventPermissionRequested", "EventPermissionResolved", "EventPlanUpdated", "EventRunCreated", "EventRunTerminal", "EventThoughtDelta", "EventToolCallBlocked", "EventToolCallCompleted", "EventToolCallFailed", "EventToolCallInProgress", "EventToolCallStarted"]

class AnvilRunEvent(BaseModel):
    """
    Contract for the JSON payload carried in each Server-Sent Event on GET /v1/runs/{run_id}/events. The SSE `id` field is the decimal `seq`; the SSE `event` field equals `type`. Every event shares the envelope fields and one payload variant selected by `type`. The stream ends after a terminal `run.completed`, `run.cancelled`, or `run.failed` event. The synthetic `events.gap` notice is emitted without an envelope `seq` when a reconnect falls behind the bounded replay buffer.
    """
    # data type: EventRunCreated
    oneof_schema_1_validator: Optional[EventRunCreated] = None
    # data type: EventMessageDelta
    oneof_schema_2_validator: Optional[EventMessageDelta] = None
    # data type: EventThoughtDelta
    oneof_schema_3_validator: Optional[EventThoughtDelta] = None
    # data type: EventPlanUpdated
    oneof_schema_4_validator: Optional[EventPlanUpdated] = None
    # data type: EventToolCallStarted
    oneof_schema_5_validator: Optional[EventToolCallStarted] = None
    # data type: EventToolCallBlocked
    oneof_schema_6_validator: Optional[EventToolCallBlocked] = None
    # data type: EventToolCallInProgress
    oneof_schema_7_validator: Optional[EventToolCallInProgress] = None
    # data type: EventToolCallFailed
    oneof_schema_8_validator: Optional[EventToolCallFailed] = None
    # data type: EventToolCallCompleted
    oneof_schema_9_validator: Optional[EventToolCallCompleted] = None
    # data type: EventPermissionRequested
    oneof_schema_10_validator: Optional[EventPermissionRequested] = None
    # data type: EventPermissionResolved
    oneof_schema_11_validator: Optional[EventPermissionResolved] = None
    # data type: EventRunTerminal
    oneof_schema_12_validator: Optional[EventRunTerminal] = None
    # data type: EventEventsGap
    oneof_schema_13_validator: Optional[EventEventsGap] = None
    actual_instance: Optional[Union[EventEventsGap, EventMessageDelta, EventPermissionRequested, EventPermissionResolved, EventPlanUpdated, EventRunCreated, EventRunTerminal, EventThoughtDelta, EventToolCallBlocked, EventToolCallCompleted, EventToolCallFailed, EventToolCallInProgress, EventToolCallStarted]] = None
    one_of_schemas: Set[str] = { "EventEventsGap", "EventMessageDelta", "EventPermissionRequested", "EventPermissionResolved", "EventPlanUpdated", "EventRunCreated", "EventRunTerminal", "EventThoughtDelta", "EventToolCallBlocked", "EventToolCallCompleted", "EventToolCallFailed", "EventToolCallInProgress", "EventToolCallStarted" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = AnvilRunEvent.model_construct()
        error_messages = []
        match = 0
        # validate data type: EventRunCreated
        if not isinstance(v, EventRunCreated):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EventRunCreated`")
        else:
            match += 1
        # validate data type: EventMessageDelta
        if not isinstance(v, EventMessageDelta):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EventMessageDelta`")
        else:
            match += 1
        # validate data type: EventThoughtDelta
        if not isinstance(v, EventThoughtDelta):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EventThoughtDelta`")
        else:
            match += 1
        # validate data type: EventPlanUpdated
        if not isinstance(v, EventPlanUpdated):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EventPlanUpdated`")
        else:
            match += 1
        # validate data type: EventToolCallStarted
        if not isinstance(v, EventToolCallStarted):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EventToolCallStarted`")
        else:
            match += 1
        # validate data type: EventToolCallBlocked
        if not isinstance(v, EventToolCallBlocked):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EventToolCallBlocked`")
        else:
            match += 1
        # validate data type: EventToolCallInProgress
        if not isinstance(v, EventToolCallInProgress):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EventToolCallInProgress`")
        else:
            match += 1
        # validate data type: EventToolCallFailed
        if not isinstance(v, EventToolCallFailed):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EventToolCallFailed`")
        else:
            match += 1
        # validate data type: EventToolCallCompleted
        if not isinstance(v, EventToolCallCompleted):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EventToolCallCompleted`")
        else:
            match += 1
        # validate data type: EventPermissionRequested
        if not isinstance(v, EventPermissionRequested):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EventPermissionRequested`")
        else:
            match += 1
        # validate data type: EventPermissionResolved
        if not isinstance(v, EventPermissionResolved):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EventPermissionResolved`")
        else:
            match += 1
        # validate data type: EventRunTerminal
        if not isinstance(v, EventRunTerminal):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EventRunTerminal`")
        else:
            match += 1
        # validate data type: EventEventsGap
        if not isinstance(v, EventEventsGap):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EventEventsGap`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in AnvilRunEvent with oneOf schemas: EventEventsGap, EventMessageDelta, EventPermissionRequested, EventPermissionResolved, EventPlanUpdated, EventRunCreated, EventRunTerminal, EventThoughtDelta, EventToolCallBlocked, EventToolCallCompleted, EventToolCallFailed, EventToolCallInProgress, EventToolCallStarted. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in AnvilRunEvent with oneOf schemas: EventEventsGap, EventMessageDelta, EventPermissionRequested, EventPermissionResolved, EventPlanUpdated, EventRunCreated, EventRunTerminal, EventThoughtDelta, EventToolCallBlocked, EventToolCallCompleted, EventToolCallFailed, EventToolCallInProgress, EventToolCallStarted. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into EventRunCreated
        try:
            instance.actual_instance = EventRunCreated.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EventMessageDelta
        try:
            instance.actual_instance = EventMessageDelta.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EventThoughtDelta
        try:
            instance.actual_instance = EventThoughtDelta.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EventPlanUpdated
        try:
            instance.actual_instance = EventPlanUpdated.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EventToolCallStarted
        try:
            instance.actual_instance = EventToolCallStarted.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EventToolCallBlocked
        try:
            instance.actual_instance = EventToolCallBlocked.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EventToolCallInProgress
        try:
            instance.actual_instance = EventToolCallInProgress.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EventToolCallFailed
        try:
            instance.actual_instance = EventToolCallFailed.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EventToolCallCompleted
        try:
            instance.actual_instance = EventToolCallCompleted.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EventPermissionRequested
        try:
            instance.actual_instance = EventPermissionRequested.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EventPermissionResolved
        try:
            instance.actual_instance = EventPermissionResolved.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EventRunTerminal
        try:
            instance.actual_instance = EventRunTerminal.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EventEventsGap
        try:
            instance.actual_instance = EventEventsGap.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into AnvilRunEvent with oneOf schemas: EventEventsGap, EventMessageDelta, EventPermissionRequested, EventPermissionResolved, EventPlanUpdated, EventRunCreated, EventRunTerminal, EventThoughtDelta, EventToolCallBlocked, EventToolCallCompleted, EventToolCallFailed, EventToolCallInProgress, EventToolCallStarted. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into AnvilRunEvent with oneOf schemas: EventEventsGap, EventMessageDelta, EventPermissionRequested, EventPermissionResolved, EventPlanUpdated, EventRunCreated, EventRunTerminal, EventThoughtDelta, EventToolCallBlocked, EventToolCallCompleted, EventToolCallFailed, EventToolCallInProgress, EventToolCallStarted. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], EventEventsGap, EventMessageDelta, EventPermissionRequested, EventPermissionResolved, EventPlanUpdated, EventRunCreated, EventRunTerminal, EventThoughtDelta, EventToolCallBlocked, EventToolCallCompleted, EventToolCallFailed, EventToolCallInProgress, EventToolCallStarted]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
