# coding: utf-8

"""
    Anvil Agent API

    Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from brokk_anvil_sdk.models.mcp_env_var import McpEnvVar
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class McpServerConfig(BaseModel):
    """
    Anvil's internal MCP server configuration shape. Per-session servers are additive to the daemon's canonical setup.
    """ # noqa: E501
    name: StrictStr
    transport: Optional[StrictStr] = 'stdio'
    command: Optional[StrictStr] = ''
    url: Optional[StrictStr] = None
    headers: Optional[List[McpEnvVar]] = None
    args: Optional[List[StrictStr]] = None
    env: Optional[List[McpEnvVar]] = None
    framing: Optional[StrictStr] = 'content-length'
    enabled: Optional[StrictBool] = True
    __properties: ClassVar[List[str]] = ["name", "transport", "command", "url", "headers", "args", "env", "framing", "enabled"]

    @field_validator('transport')
    def transport_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['stdio', 'http', 'sse']):
            raise ValueError("must be one of enum values ('stdio', 'http', 'sse')")
        return value

    @field_validator('framing')
    def framing_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['content-length', 'line']):
            raise ValueError("must be one of enum values ('content-length', 'line')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of McpServerConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in headers (list)
        _items = []
        if self.headers:
            for _item_headers in self.headers:
                if _item_headers:
                    _items.append(_item_headers.to_dict())
            _dict['headers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in env (list)
        _items = []
        if self.env:
            for _item_env in self.env:
                if _item_env:
                    _items.append(_item_env.to_dict())
            _dict['env'] = _items
        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of McpServerConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "transport": obj.get("transport") if obj.get("transport") is not None else 'stdio',
            "command": obj.get("command") if obj.get("command") is not None else '',
            "url": obj.get("url"),
            "headers": [McpEnvVar.from_dict(_item) for _item in obj["headers"]] if obj.get("headers") is not None else None,
            "args": obj.get("args"),
            "env": [McpEnvVar.from_dict(_item) for _item in obj["env"]] if obj.get("env") is not None else None,
            "framing": obj.get("framing") if obj.get("framing") is not None else 'content-length',
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True
        })
        return _obj
