# coding: utf-8

"""
    Anvil Agent API

    Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from brokk_anvil_sdk.models.model_pricing import ModelPricing
from brokk_anvil_sdk.models.model_service_tiers_inner import ModelServiceTiersInner
from brokk_anvil_sdk.models.model_supported_reasoning_levels_inner import ModelSupportedReasoningLevelsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Model(BaseModel):
    """
    One discovered model. Ids are wire-tagged `<source>::<id>` (for example `codex::gpt-5-codex`, `ollama::llama3:latest`).
    """ # noqa: E501
    id: StrictStr
    default_reasoning_level: Optional[StrictStr]
    supported_reasoning_levels: List[ModelSupportedReasoningLevelsInner]
    service_tiers: List[ModelServiceTiersInner]
    supports_images: Optional[StrictBool]
    context_length: Optional[Annotated[int, Field(strict=True, ge=0)]]
    pricing: Optional[ModelPricing]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "default_reasoning_level", "supported_reasoning_levels", "service_tiers", "supports_images", "context_length", "pricing"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Model from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in supported_reasoning_levels (list)
        _items = []
        if self.supported_reasoning_levels:
            for _item_supported_reasoning_levels in self.supported_reasoning_levels:
                if _item_supported_reasoning_levels:
                    _items.append(_item_supported_reasoning_levels.to_dict())
            _dict['supported_reasoning_levels'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in service_tiers (list)
        _items = []
        if self.service_tiers:
            for _item_service_tiers in self.service_tiers:
                if _item_service_tiers:
                    _items.append(_item_service_tiers.to_dict())
            _dict['service_tiers'] = _items
        # override the default output from pydantic by calling `to_dict()` of pricing
        if self.pricing:
            _dict['pricing'] = self.pricing.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if default_reasoning_level (nullable) is None
        # and model_fields_set contains the field
        if self.default_reasoning_level is None and "default_reasoning_level" in self.model_fields_set:
            _dict['default_reasoning_level'] = None

        # set to None if supports_images (nullable) is None
        # and model_fields_set contains the field
        if self.supports_images is None and "supports_images" in self.model_fields_set:
            _dict['supports_images'] = None

        # set to None if context_length (nullable) is None
        # and model_fields_set contains the field
        if self.context_length is None and "context_length" in self.model_fields_set:
            _dict['context_length'] = None

        # set to None if pricing (nullable) is None
        # and model_fields_set contains the field
        if self.pricing is None and "pricing" in self.model_fields_set:
            _dict['pricing'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Model from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "default_reasoning_level": obj.get("default_reasoning_level"),
            "supported_reasoning_levels": [ModelSupportedReasoningLevelsInner.from_dict(_item) for _item in obj["supported_reasoning_levels"]] if obj.get("supported_reasoning_levels") is not None else None,
            "service_tiers": [ModelServiceTiersInner.from_dict(_item) for _item in obj["service_tiers"]] if obj.get("service_tiers") is not None else None,
            "supports_images": obj.get("supports_images"),
            "context_length": obj.get("context_length"),
            "pricing": ModelPricing.from_dict(obj["pricing"]) if obj.get("pricing") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
