# coding: utf-8

"""
    Anvil Agent API

    Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from brokk_anvil_sdk.models.permission_option import PermissionOption
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Permission(BaseModel):
    """
    Permission
    """ # noqa: E501
    id: StrictStr
    run_id: StrictStr
    session_id: StrictStr
    tool_name: StrictStr
    tool_call_id: StrictStr
    input: Optional[Any]
    permission_notice: Optional[StrictStr]
    options: List[PermissionOption]
    created_at_ms: Annotated[int, Field(strict=True, ge=0)]
    status: StrictStr
    __properties: ClassVar[List[str]] = ["id", "run_id", "session_id", "tool_name", "tool_call_id", "input", "permission_notice", "options", "created_at_ms", "status"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending']):
            raise ValueError("must be one of enum values ('pending')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Permission from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in options (list)
        _items = []
        if self.options:
            for _item_options in self.options:
                if _item_options:
                    _items.append(_item_options.to_dict())
            _dict['options'] = _items
        # set to None if input (nullable) is None
        # and model_fields_set contains the field
        if self.input is None and "input" in self.model_fields_set:
            _dict['input'] = None

        # set to None if permission_notice (nullable) is None
        # and model_fields_set contains the field
        if self.permission_notice is None and "permission_notice" in self.model_fields_set:
            _dict['permission_notice'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Permission from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "run_id": obj.get("run_id"),
            "session_id": obj.get("session_id"),
            "tool_name": obj.get("tool_name"),
            "tool_call_id": obj.get("tool_call_id"),
            "input": obj.get("input"),
            "permission_notice": obj.get("permission_notice"),
            "options": [PermissionOption.from_dict(_item) for _item in obj["options"]] if obj.get("options") is not None else None,
            "created_at_ms": obj.get("created_at_ms"),
            "status": obj.get("status")
        })
        return _obj
