# coding: utf-8

"""
    Anvil Agent API

    Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, Optional
from typing_extensions import Annotated
from brokk_anvil_sdk.models.usage import Usage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Run(BaseModel):
    """
    Run
    """ # noqa: E501
    id: StrictStr
    session_id: StrictStr
    status: StrictStr
    stop_reason: Optional[StrictStr]
    error: Optional[StrictStr]
    result_text: Optional[StrictStr]
    structured_output: Optional[Any]
    usage: Optional[Usage]
    created_at_ms: Annotated[int, Field(strict=True, ge=0)]
    finished_at_ms: Optional[Annotated[int, Field(strict=True, ge=0)]]
    last_seq: Annotated[int, Field(strict=True, ge=0)]
    __properties: ClassVar[List[str]] = ["id", "session_id", "status", "stop_reason", "error", "result_text", "structured_output", "usage", "created_at_ms", "finished_at_ms", "last_seq"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['running', 'completed', 'cancelled', 'failed']):
            raise ValueError("must be one of enum values ('running', 'completed', 'cancelled', 'failed')")
        return value

    @field_validator('stop_reason')
    def stop_reason_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['end_turn', 'max_turns', 'time_limit', 'cancelled', 'error']):
            raise ValueError("must be one of enum values ('end_turn', 'max_turns', 'time_limit', 'cancelled', 'error')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Run from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        # set to None if stop_reason (nullable) is None
        # and model_fields_set contains the field
        if self.stop_reason is None and "stop_reason" in self.model_fields_set:
            _dict['stop_reason'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if result_text (nullable) is None
        # and model_fields_set contains the field
        if self.result_text is None and "result_text" in self.model_fields_set:
            _dict['result_text'] = None

        # set to None if structured_output (nullable) is None
        # and model_fields_set contains the field
        if self.structured_output is None and "structured_output" in self.model_fields_set:
            _dict['structured_output'] = None

        # set to None if usage (nullable) is None
        # and model_fields_set contains the field
        if self.usage is None and "usage" in self.model_fields_set:
            _dict['usage'] = None

        # set to None if finished_at_ms (nullable) is None
        # and model_fields_set contains the field
        if self.finished_at_ms is None and "finished_at_ms" in self.model_fields_set:
            _dict['finished_at_ms'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Run from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "session_id": obj.get("session_id"),
            "status": obj.get("status"),
            "stop_reason": obj.get("stop_reason"),
            "error": obj.get("error"),
            "result_text": obj.get("result_text"),
            "structured_output": obj.get("structured_output"),
            "usage": Usage.from_dict(obj["usage"]) if obj.get("usage") is not None else None,
            "created_at_ms": obj.get("created_at_ms"),
            "finished_at_ms": obj.get("finished_at_ms"),
            "last_seq": obj.get("last_seq")
        })
        return _obj
