# coding: utf-8

"""
    Anvil Agent API

    Versioned REST surface of the Anvil agent runtime (`anvil serve`). This document, together with the companion SSE event schema (`anvil.v1.events.schema.json`), is the authoritative wire contract: official SDK wire layers are generated from these artifacts, and the black-box conformance suite (`tests/http_conformance.rs`) validates a running daemon against them. See COMPATIBILITY.md for the evolution rules that govern what may change within `/v1`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from brokk_anvil_sdk.models.history_turn import HistoryTurn
from brokk_anvil_sdk.models.usage import Usage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Session(BaseModel):
    """
    Session
    """ # noqa: E501
    id: StrictStr
    cwd: StrictStr
    additional_directories: List[StrictStr]
    model: StrictStr
    behavior_mode: StrictStr
    permission_mode: StrictStr
    reasoning_effort: Optional[StrictStr]
    service_tier: Optional[StrictStr]
    title: Optional[StrictStr]
    created_at_ms: Annotated[int, Field(strict=True, ge=0)]
    modified_at_ms: Annotated[int, Field(strict=True, ge=0)]
    updated_at: Optional[StrictStr] = Field(description="RFC 3339 rendering of `modified_at_ms`.")
    history_turns: Annotated[int, Field(strict=True, ge=0)]
    usage: Usage
    usage_cost_usd: Optional[Union[StrictFloat, StrictInt]]
    history: Optional[List[HistoryTurn]] = Field(default=None, description="Present only on `load` responses and `?include_history=true` inspections.")
    __properties: ClassVar[List[str]] = ["id", "cwd", "additional_directories", "model", "behavior_mode", "permission_mode", "reasoning_effort", "service_tier", "title", "created_at_ms", "modified_at_ms", "updated_at", "history_turns", "usage", "usage_cost_usd", "history"]

    @field_validator('behavior_mode')
    def behavior_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['LUTZ', 'PLAN']):
            raise ValueError("must be one of enum values ('LUTZ', 'PLAN')")
        return value

    @field_validator('permission_mode')
    def permission_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['default', 'auto', 'acceptEdits', 'readOnly', 'bypassPermissions']):
            raise ValueError("must be one of enum values ('default', 'auto', 'acceptEdits', 'readOnly', 'bypassPermissions')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Session from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in history (list)
        _items = []
        if self.history:
            for _item_history in self.history:
                if _item_history:
                    _items.append(_item_history.to_dict())
            _dict['history'] = _items
        # set to None if reasoning_effort (nullable) is None
        # and model_fields_set contains the field
        if self.reasoning_effort is None and "reasoning_effort" in self.model_fields_set:
            _dict['reasoning_effort'] = None

        # set to None if service_tier (nullable) is None
        # and model_fields_set contains the field
        if self.service_tier is None and "service_tier" in self.model_fields_set:
            _dict['service_tier'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        # set to None if usage_cost_usd (nullable) is None
        # and model_fields_set contains the field
        if self.usage_cost_usd is None and "usage_cost_usd" in self.model_fields_set:
            _dict['usage_cost_usd'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Session from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "cwd": obj.get("cwd"),
            "additional_directories": obj.get("additional_directories"),
            "model": obj.get("model"),
            "behavior_mode": obj.get("behavior_mode"),
            "permission_mode": obj.get("permission_mode"),
            "reasoning_effort": obj.get("reasoning_effort"),
            "service_tier": obj.get("service_tier"),
            "title": obj.get("title"),
            "created_at_ms": obj.get("created_at_ms"),
            "modified_at_ms": obj.get("modified_at_ms"),
            "updated_at": obj.get("updated_at"),
            "history_turns": obj.get("history_turns"),
            "usage": Usage.from_dict(obj["usage"]) if obj.get("usage") is not None else None,
            "usage_cost_usd": obj.get("usage_cost_usd"),
            "history": [HistoryTurn.from_dict(_item) for _item in obj["history"]] if obj.get("history") is not None else None
        })
        return _obj
