from typing import Awaitable

__version__: str
class NativeError(Exception): ...
class NativeClient:
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    def infer(self, raw: str) -> Awaitable[str]: ...

